set(DEFAULT_CLANG_FORMAT clang-format)
set(DEFAULT_LLVM_CONFIG llvm-config)

if(DEFINED CLANG_PREFIX)
  message(STATUS "CLANG_PREFIX: ${CLANG_PREFIX}")
  set(CMAKE_CXX_COMPILER "${CLANG_PREFIX}/clang++")
  set(CMAKE_C_COMPILER "${CLANG_PREFIX}/clang")
  set(CMAKE_ASM_COMPILER "${CLANG_PREFIX}/clang")
  set(DEFAULT_LLVM_CONFIG "${CLANG_PREFIX}/llvm-config")
  set(DEFAULT_CLANG_FORMAT "${CLANG_PREFIX}/clang-format")
endif()

set(CLANG_FORMAT ${DEFAULT_CLANG_FORMAT} CACHE STRING "clang-format to use")
message(STATUS "CLANG_FORMAT: ${CLANG_FORMAT}")

set(LLVM_CONFIG ${DEFAULT_LLVM_CONFIG} CACHE STRING "llvm-config to use")
message(STATUS "LLVM_CONFIG: ${LLVM_CONFIG}")

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
