name: Build + Test w/clang (Sanitized)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: apt-get dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip wget cmake lsb-release software-properties-common gnupg ninja-build
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16
        sudo apt-get install clang-format-16
    - name: Pip install requirements
      run: |
        pip install -r requirements.txt
    - name: CMake
      run: |
        mkdir build
        cd build
        cmake .. -GNinja -DCMAKE_C_COMPILER=clang-16 -DCMAKE_CXX_COMPILER=clang++-16 \
          -DLLVM_CONFIG=llvm-config-16 -DCLANG_FORMAT=clang-format-16 \
          -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" -DFILECHECK=FileCheck-16
    - name: Ninja build
      run: |
        cd build
        ninja
    - name: Run tests
      run: |
        cd build
        ninja check
    - name: Format check
      run: |
        cd build
        ninja format-check
